name: Build MXE Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile.mxe'
      - '.github/workflows/build-mxe-image.yml'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.mxe
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/mxe-gtk3-portaudio:latest
          ghcr.io/${{ github.repository_owner }}/mxe-gtk3-portaudio:${{ github.sha }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/mxe-gtk3-portaudio:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/mxe-gtk3-portaudio:buildcache,mode=max
