name: Build Windows

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          git
          make
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-gtk3
          mingw-w64-ucrt-x86_64-portaudio
          msys2-runtime
          pkgconf
          mingw-w64-ucrt-x86_64-gsettings-desktop-schemas
          glib2
    
    - name: Build project
      run: make

    - name: Compile schemas
      run: |
        glib-compile-schemas /ucrt64/share/glib-2.0/schemas
    
    - name: Create artifact
      run: |
        mkdir -p artifact
        cp build/dav.exe artifact/
        ldd ./build/dav.exe | grep home | awk '{print $1}' | xargs -I {} cp /ucrt64/bin/{} artifact/
        cp -r /ucrt64/share/glib-2.0/schemas artifact/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dav-windows-build
        path: artifact/
        if-no-files-found: error